module.exports = [
{name:"Early metazoan cell type diversity and the evolution of multicellular gene regulation"},
{name:"Profiling cellular diversity in sponges informs animal cell type and nervous system evolution"},
{name:"Whole-animal multiplexed single-cell RNA-seq reveals transcriptional shifts across Clytia medusa cell types"},
{name:"Cnidarian Cell Type Diversity and Regulation Revealed by Whole Organism Single Cell RNA-Seq"},
{name:"Lineage dynamics of the endosymbiotic cell type in the soft coral Xenia"},
{name:"A stony coral cell atlas illuminates the molecular and cellular basis of coral symbiosis, calcification, and immunity"},
{name:"Stem cell differentiation trajectories in Hydra resolved at single-cell resolution"},
{name:"Cell type transcriptome atlas for the planarian Schmidtea mediterranea"},
{name:"Cell type atlas and lineage tree of a whole complex animal by single-cell transcriptomics"},
{name:"A single-cell RNAseq atlas of Schistosoma mansoni identifies a key regulator of blood feeding"},
{name:"Single-cell atlas of the first intra-mammalian developmental stage of the human parasite Schistosoma mansoni"},
{name:"Cell type diversity in a developing octopus brain"},
{name:"Single-Cell RNA Sequencing Atlas From a Bivalve Larva Enhances Classical Cell Lineage Studies"},
{name:"Single-cell RNA sequencing of the Strongylocentrotus purpuratus larva reveals the blueprint of major cell types and nervous system of a non-chordate deuterostome"},
{name:"A single cell RNA sequencing resource for early sea urchin development"},
{name:"Developmental single-cell transcriptomics in the Lytechinus variegatus sea urchin embryo"},
{name:"Single-cell transcriptome profiling of the Ciona larval brain"},
{name:"Comprehensive single-cell transcriptome lineages of a proto-vertebrate"},
{name:"A single-cell analysis of the molecular lineage of chordate embryogenesis"},
{name:"Joint profiling of gene expression and chromatin accessibility of amphioxus development at single cell resolution"},
{name:"Simultaneous single-cell profiling of lineages and cell types in the vertebrate brain"},
{name:"Emergence of neuronal diversity during vertebrate brain development"},
{name:"Single-cell sequencing of radial glia progeny reveals the diversity of newborn neurons in the adult zebrafish brain"},
{name:"Single-cell mapping of gene expression landscapes and lineage in the zebrafish embryo"},
{name:"A single-cell transcriptome atlas for zebrafish development"},
{name:"Single-cell reconstruction of developmental trajectories during zebrafish embryogenesis"},
{name:"Construction of a cross-species cell landscape at single-cell level"},
{name:"A single cell transcriptome atlas of the developing zebrafish hindbrain"},
{name:"Gene family evolution underlies cell-type diversification in the hypothalamus of teleosts"},
{name:"A cell atlas of microbe-responsive processes in the zebrafish intestine"},
{name:"Evolution of pallium, hippocampus, and cortical cell types revealed by single-cell transcriptomics in reptiles"},
{name:"The dynamics of gene expression in vertebrate embryogenesis at single-cell resolution"},
{name:"Chromatin accessibility dynamics and single cell RNA-Seq reveal new regulators of regeneration in neural progenitors"},
{name:"Identification of a regenerationorganizing cell in the Xenopus tail"},
{name:"Cell landscape of larval and adult Xenopus laevis at single-cell resolution"},
{name:"Single-Cell Atlas of the Chinese Tongue Sole (Cynoglossus semilaevis) Ovary Reveals Transcriptional Programs of Oogenesis in Fish"},
]
