module.exports = [
    { index: 1 ,  name:'Amphimedon queenslandica',           DBKey:'', exampleGene: [],},
    { index: 2 ,  name:'Astyanax mexicanus',                 DBKey:'', exampleGene: [],},
    { index: 3 ,  name:'Branchiostoma floridae',             DBKey:'', exampleGene: [],},
    { index: 4 ,  name:'Ciona intestinalis',                 DBKey:'', exampleGene: [],},
    { index: 5 ,  name:'Ciona robusta(intestinalis Type A)', DBKey:'', exampleGene: [],},
    { index: 6 ,  name:'Ciona savignyi',                     DBKey:'', exampleGene: [],},
    { index: 7 ,  name:'Clytia medusa',                      DBKey:'', exampleGene: [],},
    { index: 8 ,  name:'Cynoglossus semilaevis',             DBKey:'', exampleGene: [],},
    { index: 9 ,  name:'Danio rerio',                        DBKey:'Zebrafish', exampleGene: [{ index:1, value:"si:ch73-252i11.3",},{ index:2, value:"PARP12",},{ index:2, value:"syn3",},],},
    { index: 10 , name:'Dreissena rostriformis',             DBKey:'', exampleGene: [],},
    { index: 11 , name:'Hydra vulgaris',                     DBKey:'', exampleGene: [],},
    { index: 12 , name:'Lytechinus variegatus',              DBKey:'', exampleGene: [],},
    { index: 13 , name:'Mnemiopsis leidyi',                  DBKey:'', exampleGene: [],},
    { index: 14 , name:'Nematostella vectensis',             DBKey:'', exampleGene: [],},
    { index: 15 , name:'Octopus vulgaris',                   DBKey:'', exampleGene: [],},
    { index: 16 , name:'Schistosoma mansoni',                DBKey:'', exampleGene: [],},
    { index: 17 , name:'Schmidtea mediterranea',             DBKey:'Schmidtea_mediterranea', exampleGene: [{ index:1, value:"dd-Smed-v4-1000-0-1",},{ index:2, value:"dd-Smed-v4-100-0-1",},{ index:3, value:"dd-Smed-v4-10001-0-1",},{ index:4, value:"dd-Smed-v4-10002-0-1",},{ index:5, value:"dd-Smed-v4-100026-0-1",},],},
    { index: 18 , name:'Spongilla lacustris',                DBKey:'', exampleGene: [],},
    { index: 19 , name:'Strongylocentrotus purpuratus',      DBKey:'', exampleGene: [],},
    { index: 20 , name:'Stylophora pistillata',              DBKey:'', exampleGene: [],},
    { index: 21 , name:'Trachemys scripta elegans',          DBKey:'', exampleGene: [],},
    { index: 22 , name:'Trichoplax adhaerens',               DBKey:'', exampleGene: [],},
    { index: 23 , name:'Xenia sp.',                          DBKey:'', exampleGene: [],},
    { index: 24 , name:'Xenopus laevis',                     DBKey:'', exampleGene: [],},
    { index: 25 , name:'Xenopus tropicalis',                 DBKey:'', exampleGene: [],},
]
