module.exports = [
    { index: 1 , name:'Amphimedon queenslandica',             },
    { index: 2 , name:'Astyanax mexicanus',             },
    { index: 3 , name:'Branchiostoma floridae',             },
    { index: 4 , name:'Ciona intestinalis',             },
    { index: 5 , name:'Ciona robusta（intestinalis Type A）',             },
    { index: 6 , name:'Ciona savignyi',             },
    { index: 7 , name:'Clytia medusa',             },
    { index: 8 , name:'Cynoglossus semilaevis',             },
    { index: 9 , name:'Danio rerio',             },
    { index: 10 , name:'Dreissena rostriformis',             },
    { index: 11 , name:'Hydra vulgaris',             },
    { index: 12 , name:'Lytechinus variegatus',             },
    { index: 13 , name:'Mnemiopsis leidyi',             },
    { index: 14 , name:'Nematostella vectensis',             },
    { index: 15 , name:'Octopus vulgaris',             },
    { index: 16 , name:'Schistosoma mansoni',             },
    { index: 17 , name:'Schmidtea mediterranea',            },
    { index: 18 , name:'Spongilla lacustris',               },
    { index: 19 , name:'Strongylocentrotus purpuratus',     },
    { index: 20 , name:'Stylophora pistillata',              },
    { index: 21 , name:'Trachemys scripta elegans',          },
    { index: 22 , name:'Trichoplax adhaerens',               },
    { index: 23, name:'Xenia sp.',                          },
    { index: 24 , name:'Xenopus laevis',                     },
    { index: 25 , name:'Xenopus tropicalis',                 },
]
